---
- hosts: all
  become: yes
  tasks:
         - name: install tree
           apt:
                  name: tree
                  state: absent
         - name: i want to start/stop tree on ubuntu node
           service:
                  name: wget
                  state: started
        
