---
- hosts: all
  become: yes
  tasks:
         - name: install tree
           apt:
                  name: tree
                  state: absent
         - name: install wget
           apt:
                  name: wget
                  state: absent
